version: '2.1'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    container_name: simple-supply-elasticsearch
    expose:
      - 9200
    ports:
      - '9200:9200'
    environment:
      ES_JAVA_OPTS: '-Xms2g -Xmx2g'
      network.bind_host: 0.0.0.0
      network.host: 0.0.0.0
      discovery.type: single-node
    networks:
      - vChain

  settings-tp:
    image: hyperledger/sawtooth-settings-tp:1.0
    container_name: sawtooth-settings-tp-testapp
    depends_on:
      - validator
    networks:
      - vChain
    entrypoint: settings-tp -vv -C tcp://validator:4004

  rest-api:
    image: hyperledger/sawtooth-rest-api:1.0
    container_name: sawtooth-rest-api-testapp
    expose:
      - 8008
    ports:
      - '8008:8008'
    depends_on:
      - validator
    networks:
      - vChain
    entrypoint: sawtooth-rest-api -vv -C tcp://validator:4004 --bind rest-api:8008

  validator:
    image: hyperledger/sawtooth-validator:1.0
    container_name: sawtooth-validator-testapp
    expose:
      - 4004
    ports:
      - '4004:4004'
    networks:
      - vChain
    command: |
      bash -c "
        if [ ! -f /etc/sawtooth/keys/validator.priv ]; then
          sawadm keygen
          sawtooth keygen my_key
          sawset genesis -k /root/.sawtooth/keys/my_key.priv
          sawadm genesis config-genesis.batch
        fi;
        sawtooth-validator -vv \
          --endpoint tcp://localhost:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800 \
          --bind consensus:tcp://eth0:5050"

networks:
  vChain:
    driver: bridge
   
